up:
	docker compose build auth-service
	docker compose build inventory-service
	docker compose build booking-service
	docker compose build mailer-service
	docker compose up

down:
	docker compose down -v
